version: '3.8'

services:
  api:
    build: .
    command: python manage.py runserver

#      python manage.py migrate;
#      python manage.py loaddata fixtures/data.json;
#      python manage.py runserver

#    volumes:
#      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
#    env_file:
#      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
#      POSTGRES_USER: skypro_l29
      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"


#  loading:
#    depends_on:
#      - db

volumes:
  postgres_data:
